#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
std::string read(const std::filesystem::path& path) {
    std::ifstream file(path, std::ios::binary);
    if (!file) throw std::runtime_error("Cannot read: " + path.string());
    return {std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>()};
}
[[noreturn]] void fail(const std::string& path, const std::string& text, std::size_t offset, const std::string& reason) {
    const auto line = 1 + std::count(text.begin(), text.begin() + static_cast<std::ptrdiff_t>(offset), '\n');
    throw std::runtime_error(path + ":" + std::to_string(line) + ":1: " + reason);
}
}
int main(int argc, char** argv) {
    try {
        if (argc < 3) throw std::runtime_error("Usage: AzureMetaGen output.hpp input.hpp ...");
        std::vector<std::string> inputs;
        std::filesystem::path componentOutput;
        for (int i = 2; i < argc; ++i) {
            if (std::string(argv[i]) == "--components-output") {
                if (++i >= argc) throw std::runtime_error("Missing component output path");
                componentOutput = argv[i];
            } else inputs.emplace_back(argv[i]);
        }
        if (inputs.empty()) throw std::runtime_error("At least one input header is required");
        std::ostringstream components;
        components << "// Generated by AzureMetaGen; edit annotated input headers.\n#pragma once\n#include \"runtime/ComponentRegistry.hpp\"\n";
        std::ostringstream output;
        output << "// Generated by AzureMetaGen; edit annotated input headers.\n#pragma once\n#include \"reflection/Registry.hpp\"\n";
        for (const auto& input : inputs) {
            output << "#include \"" << std::filesystem::path(input).generic_string() << "\"\n";
            components << "#include \"" << std::filesystem::path(input).generic_string() << "\"\n";
        }
        components << "namespace azurerender {\ninline void registerGeneratedComponents(ComponentRegistry& registry) {\n";
        output << "namespace azurerender::reflection {\ninline void registerGeneratedTypes(Registry& registry) {\n";
        std::set<std::string> names;
        const std::regex ns(R"meta(namespace\s+([A-Za-z_][A-Za-z0-9_:]*)\s*\{)meta");
        const std::regex types(R"meta(AZURE_TYPE\s*\(\s*"([A-Za-z0-9_.-]+)"\s*,\s*([0-9]+)\s*\)\s*struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{([\s\S]*?)\n\};)meta");
        const std::regex fields(R"meta(AZURE_FIELD\s*\(\s*("[^"\r\n]*")\s*,\s*([-+0-9.eE]+)\s*,\s*([-+0-9.eE]+)\s*\)\s*(?:AZURE_FIELD_META\s*\(\s*("[^"\r\n]*")\s*,\s*("[^"\r\n]*")\s*,\s*(true|false)\s*,\s*(true|false)\s*\)\s*)?(?:AZURE_FIELD_REFERENCE\s*\(\s*("[^"\r\n]*")\s*,\s*("[^"\r\n]*")\s*,\s*("[^"\r\n]*")\s*\)\s*)?(?:AZURE_FIELD_EDITOR\s*\(\s*("[^"\r\n]*")\s*,\s*([0-9]+)\s*,\s*(true|false)\s*\)\s*)?([^;=\{]+?)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:[=\{;]))meta");
        for (const auto& input : inputs) {
            const std::string path = std::filesystem::path(input).generic_string(), text = read(path);
            std::smatch space;
            if (!std::regex_search(text, space, ns)) fail(path, text, 0, "Expected one qualified namespace");
            std::size_t typeCount = 0;
            for (auto it = std::sregex_iterator(text.begin(), text.end(), types); it != std::sregex_iterator(); ++it) {
                const auto& match = *it;
                const std::string name = match[1], version = match[2], qualified = space[1].str() + "::" + match[3].str(), body = match[4];
                if (!names.insert(name).second || std::stoul(version) == 0)
                    fail(path, text, static_cast<std::size_t>(match.position()), "Duplicate name or invalid schema version: " + name);
                output << "registry.addType(reflectedType<" << qualified << "> (\"" << name << "\", " << version << ", {\n";
                components << "registry.bind<" << qualified << ">(\"" << name << "\");\n";
                std::set<std::string> members;
                std::size_t count = 0;
                for (auto field = std::sregex_iterator(body.begin(), body.end(), fields); field != std::sregex_iterator(); ++field) {
                    std::string type = (*field)[14], member = (*field)[15];
                    type = std::regex_replace(type, std::regex("\\s+"), "");
                    const std::set<std::string> supported{"float", "bool", "std::string", "std::uint32_t", "std::array<float,3>"};
                    if (!supported.count(type) || !members.insert(member).second)
                        fail(path, text, static_cast<std::size_t>(match.position(4) + field->position()), "Unsupported or duplicate field: " + type + " " + member);
                    const bool reference=(*field)[8].matched;
                    if(reference && type!="std::string")fail(path,text,static_cast<std::size_t>(match.position(4)+field->position()),"Reference annotations require string fields");
                    if((*field)[11].matched)output << "withEditor(";
                    if(reference)output << "withReference(";
                    output << "withMetadata(property<" << qualified << "> (\"" << member << "\", " << (*field)[1].str()
                           << ", &" << qualified << "::" << member << ", " << (*field)[2].str() << ", " << (*field)[3].str() << "), "
                           << ((*field)[4].matched ? (*field)[4].str() : "\"\"") << ", "
                           << ((*field)[5].matched ? (*field)[5].str() : "\"\"") << ", "
                           << ((*field)[6].matched ? (*field)[6].str() : "false") << ", "
                           << ((*field)[7].matched ? (*field)[7].str() : "true") << ")";
                    if(reference){
                        output << ", " << (*field)[8].str() << ", {";
                        const auto types=(*field)[9].str();std::istringstream values(types.substr(1,types.size()-2));std::string value;bool first=true;
                        while(std::getline(values,value,'|'))if(!value.empty()){if(!first)output << ", ";output << "\"" << value << "\"";first=false;}
                        output << "}, " << (*field)[10].str() << ")";
                    }
                    if((*field)[11].matched)output << ", " << (*field)[11].str() << ", " << (*field)[12].str() << ", " << (*field)[13].str() << ")";
                    output << ",\n";
                    ++count;
                }
                const std::regex fieldAnnotation(R"(\bAZURE_FIELD\s*\()");
                const auto expected = static_cast<std::size_t>(std::distance(
                    std::sregex_iterator(body.begin(), body.end(), fieldAnnotation), std::sregex_iterator()));
                if (expected != count) fail(path, text, static_cast<std::size_t>(match.position()), "Malformed field annotation");
                output << "}));\n";
                ++typeCount;
            }
            std::size_t expected = 0, cursor = 0;
            while ((cursor = text.find("AZURE_TYPE(", cursor)) != std::string::npos) { ++expected; cursor += 11; }
            if (expected != typeCount) fail(path, text, 0, "Malformed type annotation");
        }
        output << "}\n} // namespace azurerender::reflection\n";
        components << "}\n} // namespace azurerender\n";
        const auto write = [](const std::filesystem::path& path, const std::string& content) {
            if (std::filesystem::exists(path) && read(path) == content) return;
            if (!path.parent_path().empty()) std::filesystem::create_directories(path.parent_path());
            const auto temporary = path.string() + ".tmp";
            { std::ofstream file(temporary, std::ios::binary); file << content; if (!file) throw std::runtime_error("Cannot write generated file"); }
            std::filesystem::copy_file(temporary, path, std::filesystem::copy_options::overwrite_existing);
            std::filesystem::remove(temporary);
        };
        write(argv[1], output.str());
        if (!componentOutput.empty()) write(componentOutput, components.str());
    } catch (const std::exception& error) { std::cerr << error.what() << '\n'; return 1; }
}
