#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
std::string read(const std::filesystem::path& path) {
    std::ifstream file(path, std::ios::binary);
    if (!file) throw std::runtime_error("Cannot read: " + path.string());
    return {std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>()};
}
[[noreturn]] void fail(const std::string& path, const std::string& text, std::size_t offset, const std::string& reason) {
    const auto line = 1 + std::count(text.begin(), text.begin() + static_cast<std::ptrdiff_t>(offset), '\n');
    throw std::runtime_error(path + ":" + std::to_string(line) + ":1: " + reason);
}
}
int main(int argc, char** argv) {
    try {
        if (argc < 3) throw std::runtime_error("Usage: AzureMetaGen output.hpp input.hpp ...");
        std::ostringstream output;
        output << "// Generated by AzureMetaGen; edit annotated input headers.\n#pragma once\n#include \"reflection/Registry.hpp\"\n";
        for (int i = 2; i < argc; ++i) output << "#include \"" << std::filesystem::path(argv[i]).generic_string() << "\"\n";
        output << "namespace azurerender::reflection {\ninline void registerGeneratedTypes(Registry& registry) {\n";
        std::set<std::string> names;
        const std::regex ns(R"meta(namespace\s+([A-Za-z_][A-Za-z0-9_:]*)\s*\{)meta");
        const std::regex types(R"meta(AZURE_TYPE\s*\(\s*"([A-Za-z0-9_.-]+)"\s*,\s*([0-9]+)\s*\)\s*struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{([\s\S]*?)\n\};)meta");
        const std::regex fields(R"meta(AZURE_FIELD\s*\(\s*("[^"\r\n]*")\s*,\s*([-+0-9.eE]+)\s*,\s*([-+0-9.eE]+)\s*\)\s*([^;=\{]+?)\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?:[=\{;]))meta");
        for (int i = 2; i < argc; ++i) {
            const std::string path = std::filesystem::path(argv[i]).generic_string(), text = read(path);
            std::smatch space;
            if (!std::regex_search(text, space, ns)) fail(path, text, 0, "Expected one qualified namespace");
            std::size_t typeCount = 0;
            for (auto it = std::sregex_iterator(text.begin(), text.end(), types); it != std::sregex_iterator(); ++it) {
                const auto& match = *it;
                const std::string name = match[1], version = match[2], qualified = space[1].str() + "::" + match[3].str(), body = match[4];
                if (!names.insert(name).second || std::stoul(version) == 0)
                    fail(path, text, static_cast<std::size_t>(match.position()), "Duplicate name or invalid schema version: " + name);
                output << "registry.addType(reflectedType<" << qualified << "> (\"" << name << "\", " << version << ", {\n";
                std::set<std::string> members;
                std::size_t count = 0;
                for (auto field = std::sregex_iterator(body.begin(), body.end(), fields); field != std::sregex_iterator(); ++field) {
                    std::string type = (*field)[4], member = (*field)[5];
                    type = std::regex_replace(type, std::regex("\\s+"), "");
                    const std::set<std::string> supported{"float", "bool", "std::string", "std::uint32_t", "std::array<float,3>"};
                    if (!supported.count(type) || !members.insert(member).second)
                        fail(path, text, static_cast<std::size_t>(match.position(4) + field->position()), "Unsupported or duplicate field: " + type + " " + member);
                    output << "property<" << qualified << "> (\"" << member << "\", " << (*field)[1].str()
                           << ", &" << qualified << "::" << member << ", " << (*field)[2].str() << ", " << (*field)[3].str() << "),\n";
                    ++count;
                }
                std::size_t expected = 0, cursor = 0;
                while ((cursor = body.find("AZURE_FIELD", cursor)) != std::string::npos) { ++expected; cursor += 11; }
                if (expected != count) fail(path, text, static_cast<std::size_t>(match.position()), "Malformed field annotation");
                output << "}));\n";
                ++typeCount;
            }
            std::size_t expected = 0, cursor = 0;
            while ((cursor = text.find("AZURE_TYPE(", cursor)) != std::string::npos) { ++expected; cursor += 11; }
            if (expected != typeCount) fail(path, text, 0, "Malformed type annotation");
        }
        output << "}\n} // namespace azurerender::reflection\n";
        const std::filesystem::path path(argv[1]);
        const std::string content = output.str();
        if (std::filesystem::exists(path) && read(path) == content) return 0;
        if (!path.parent_path().empty()) std::filesystem::create_directories(path.parent_path());
        const auto temporary = path.string() + ".tmp";
        { std::ofstream file(temporary, std::ios::binary); file << content; if (!file) throw std::runtime_error("Cannot write generated file"); }
        // All validation precedes replacement; failed inputs retain the prior output.
        std::filesystem::copy_file(temporary, path, std::filesystem::copy_options::overwrite_existing);
        std::filesystem::remove(temporary);
    } catch (const std::exception& error) { std::cerr << error.what() << '\n'; return 1; }
}
