"""Generate checked C++ and Slang scalar layouts from one type description."""
import argparse
import json
from pathlib import Path
import sys
from compile_shader_module import layout_types


def generate(description):
    types=layout_types(description)
    cpp=['// Generated by tools/generate_shader_types.py.','#pragma once','#include <cstddef>','#include <cstdint>',
         'namespace azurerender::shader {']
    slang=['// Generated by tools/generate_shader_types.py.']
    for name,value in types.items():
        cpp.append('struct '+name+' {');slang.append('public struct '+name+' {')
        for field in value['fields']:
            if field['type']=='float32':
                default=format(field['default'],'.9g')
                if '.' not in default and 'e' not in default: default+='.'
                ctype,ltype,default='float','float',default+'F'
            else: ctype,ltype,default='std::uint32_t','uint',str(field['default'])+'U'
            cpp.append('    '+ctype+' '+field['name']+' = '+default+';')
            slang.append('    public '+ltype+' '+field['name']+';')
        cpp.append('};');slang.append('};')
        cpp.append(f'static_assert(sizeof({name}) == {value["size"]});')
        cpp.append(f'static_assert(alignof({name}) == {value["alignment"]});')
        for field in value['fields']:cpp.append(f'static_assert(offsetof({name}, {field["name"]}) == {field["offset"]});')
    cpp.append('}')
    return '\n'.join(cpp)+'\n','\n'.join(slang)+'\n'


def main():
    parser=argparse.ArgumentParser(__doc__)
    parser.add_argument('--description',type=Path,required=True);parser.add_argument('--cpp',type=Path,required=True)
    parser.add_argument('--slang',type=Path,required=True);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    try:
        generated=generate(json.loads(args.description.read_text(encoding='utf-8')))
        for path,data in zip((args.cpp,args.slang),generated):
            if args.check:
                if not path.is_file() or path.read_text(encoding='utf-8')!=data:raise ValueError('Generated shader layout differs: '+str(path))
            else:
                path.parent.mkdir(parents=True,exist_ok=True);path.write_text(data,encoding='utf-8')
        return 0
    except (ValueError,TypeError,KeyError,OSError) as error:
        print(str(error),file=sys.stderr);return 1


if __name__=='__main__':raise SystemExit(main())
