// Generated by tools/generate_script_bindings.py.
// Binding description SHA256: 0702310e977fabbc5a72f17dc961510d61d188bc6042cb1145c2002a770b44de
#nullable enable
using System;
using System.Text.Json.Nodes;
namespace Azure.Engine;
public sealed partial class AzureObject {
    public const uint BindingVersion = 1;
    public string Id => Host.Invoke(Handle,"id",new JsonArray())!.GetValue<string>();
    public AzureObject? Find(string id) { return ObjectResult(Host.Invoke(Handle,"find",new JsonArray(JsonValue.Create(id)))); }
    public string InteractionTarget() { return Host.Invoke(Handle,"interaction_target",new JsonArray())!.GetValue<string>(); }
    public bool Has(string type) { return Host.Invoke(Handle,"has",new JsonArray(JsonValue.Create(type)))!.GetValue<bool>(); }
    public void RemoveComponent(string type) { Host.Invoke(Handle,"remove_component",new JsonArray(JsonValue.Create(type))); }
    public void Spawn(string id,string resource,float[] position) { Host.Invoke(Handle,"spawn",new JsonArray(JsonValue.Create(id),JsonValue.Create(resource),ArrayValue(position))); }
    public bool Alive() { return Host.Invoke(Handle,"alive",new JsonArray())!.GetValue<bool>(); }
    public bool Action(string action) { return Host.Invoke(Handle,"action",new JsonArray(JsonValue.Create(action)))!.GetValue<bool>(); }
    public bool Pressed(string action) { return Host.Invoke(Handle,"pressed",new JsonArray(JsonValue.Create(action)))!.GetValue<bool>(); }
    public void Move(float x,float z,bool jump) { Host.Invoke(Handle,"move",new JsonArray(JsonValue.Create(x),JsonValue.Create(z),JsonValue.Create(jump))); }
    public void Destroy() { Host.Invoke(Handle,"destroy",new JsonArray()); }
    public void LoadLevel(string reference) { Host.Invoke(Handle,"load_level",new JsonArray(JsonValue.Create(reference))); }
    public void AudioPlay() { Host.Invoke(Handle,"audio_play",new JsonArray()); }
    public void UiText(string id,string text) { Host.Invoke(Handle,"ui_text",new JsonArray(JsonValue.Create(id),JsonValue.Create(text))); }
    public JsonNode? Get(string type,string field) { return Host.Invoke(Handle,"get",new JsonArray(JsonValue.Create(type),JsonValue.Create(field))); }
    public void Set(string type,string field,JsonNode? value) { Host.Invoke(Handle,"set",new JsonArray(JsonValue.Create(type),JsonValue.Create(field),value?.DeepClone())); }
}
