// Generated by tools/generate_script_bindings.py.
namespace Azure.Engine; internal static class BindingContract { internal const string Hash="0702310e977fabbc5a72f17dc961510d61d188bc6042cb1145c2002a770b44de"; }
