"""Generate both language surfaces from the versioned binding description."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT=Path(__file__).resolve().parents[1]
TYPES={'string','boolean','number','array','value'}
RESULTS=TYPES|{'void','object?'}

def validate(document):
    if set(document)!={'schemaVersion','apiVersion','properties','methods'}:
        raise ValueError('Unknown or missing description fields')
    if type(document['schemaVersion']) is not int or document['schemaVersion']!=1:
        raise ValueError('Unsupported schema version')
    if type(document['apiVersion']) is not int or document['apiVersion']!=1:
        raise ValueError('Unsupported binding API version')
    if document['properties']!=[{'name':'id','type':'string','access':'read-only'}]:
        raise ValueError('Object identity requires read-only string access')
    methods=document['methods']
    if not isinstance(methods,list) or not methods or len(methods)>128:
        raise ValueError('Invalid method count')
    names={'id'};managed_names={'Id'}
    for method in methods:
        if set(method)!={'name','managed','parameters','result','mutating'}:
            raise ValueError('Unknown or missing method fields')
        for name,pattern,seen in ((method['name'],r'[a-z][a-z0-9_]*',names),
                                  (method['managed'],r'[A-Z][A-Za-z0-9]*',managed_names)):
            if not isinstance(name,str) or not re.fullmatch(pattern,name) or name in seen:
                raise ValueError('Invalid or duplicate binding name')
            seen.add(name)
        if method['result'] not in RESULTS or type(method['mutating']) is not bool:
            raise ValueError('Invalid result type or permission')
        params=method['parameters']
        if not isinstance(params,list) or len(params)>3:
            raise ValueError('Invalid parameter count')
        fields=set()
        for param in params:
            if set(param)!={'name','type'} or param['type'] not in TYPES:
                raise ValueError('Invalid parameter type')
            name=param['name']
            if not isinstance(name,str) or not re.fullmatch(r'[a-z][A-Za-z0-9]*',name) or name in fields:
                raise ValueError('Invalid or duplicate parameter name')
            fields.add(name)
    return document

def artifacts(document):
    digest=hashlib.sha256(json.dumps(document,sort_keys=True,separators=(',',':')).encode()).hexdigest()
    cpp=['// Generated by tools/generate_script_bindings.py.','// Binding description SHA256: '+digest,
         '#pragma once','#include "scripting/BindingDescriptor.hpp"','namespace azurerender {',
         'inline constexpr unsigned kScriptBindingVersion = '+str(document['apiVersion'])+';',
         'inline constexpr const char* kScriptBindingHash = "'+digest+'";',
         'inline constexpr BindingDescriptor kScriptBindings[] = {']
    for method in document['methods']:
        types=[json.dumps(p['type']) for p in method['parameters']]
        types+=['nullptr']*(3-len(types))
        cpp.append('    {'+json.dumps(method['name'])+','+json.dumps(method['result'])+','+
                   str(method['mutating']).lower()+',{'+','.join(types)+'},'+str(len(method['parameters']))+'},')
    cpp+=['};','} // namespace azurerender','']
    cs=['// Generated by tools/generate_script_bindings.py.','// Binding description SHA256: '+digest,
        '#nullable enable','using System;','using System.Text.Json.Nodes;','namespace Azure.Engine;',
        'public sealed partial class AzureObject {',
        '    public const uint BindingVersion = '+str(document['apiVersion'])+';',
        '    public string Id => Host.Invoke(Handle,"id",new JsonArray())!.GetValue<string>();']
    managed_type={'string':'string','boolean':'bool','number':'float','array':'float[]','value':'JsonNode?'}
    returns={**managed_type,'void':'void','object?':'AzureObject?'}
    for method in document['methods']:
        params=method['parameters'];args=[]
        for p in params:
            if p['type']=='value':args.append(p['name']+'?.DeepClone()')
            elif p['type']=='array':args.append('ArrayValue('+p['name']+')')
            else:args.append('JsonValue.Create('+p['name']+')')
        invocation='Host.Invoke(Handle,'+json.dumps(method['name'])+',new JsonArray('+','.join(args)+'))'
        signature='    public '+returns[method['result']]+' '+method['managed']+'('+','.join(managed_type[p['type']]+' '+p['name'] for p in params)+')'
        result=method['result']
        if result=='void':body=invocation+';'
        elif result=='object?':body='return ObjectResult('+invocation+');'
        elif result=='value':body='return '+invocation+';'
        else:body='return '+invocation+'!.GetValue<'+returns[result]+'>();'
        cs.append(signature+' { '+body+' }')
    cs+=['}','']
    return {'src/scripting/GeneratedBindings.hpp':'\n'.join(cpp),
            'managed/EngineBindings/BindingContract.g.cs':'// Generated by tools/generate_script_bindings.py.\nnamespace Azure.Engine; internal static class BindingContract { internal const string Hash="'+digest+'"; }\n',
            'managed/EngineBindings/AzureObject.g.cs':'\n'.join(cs)}

def main():
    parser=argparse.ArgumentParser(__doc__)
    parser.add_argument('--schema',type=Path,default=ROOT/'schemas/script_bindings.json')
    parser.add_argument('--output-root',type=Path,default=ROOT)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    try:outputs=artifacts(validate(json.loads(args.schema.read_text(encoding='utf-8-sig'))))
    except (ValueError,TypeError,KeyError,OSError) as error:
        print('Binding description rejected: '+str(error),file=sys.stderr);return 3
    for name,content in outputs.items():
        path=args.output_root/name;data=content.encode()
        if args.check:
            if not path.is_file() or path.read_bytes().replace(b'\r\n',b'\n')!=data:
                print('Generated binding drift: '+name,file=sys.stderr);return 2
        else:
            path.parent.mkdir(parents=True,exist_ok=True)
            temporary=path.with_suffix(path.suffix+'.tmp');temporary.write_bytes(data);temporary.replace(path)
    print('Script binding artifacts verified' if args.check else 'Script binding artifacts generated')
    return 0

if __name__=='__main__':raise SystemExit(main())
