// Generated by tools/generate_script_bindings.py.
// Binding description SHA256: 0702310e977fabbc5a72f17dc961510d61d188bc6042cb1145c2002a770b44de
#pragma once
#include "scripting/BindingDescriptor.hpp"
namespace azurerender {
inline constexpr unsigned kScriptBindingVersion = 1;
inline constexpr const char* kScriptBindingHash = "0702310e977fabbc5a72f17dc961510d61d188bc6042cb1145c2002a770b44de";
inline constexpr BindingDescriptor kScriptBindings[] = {
    {"find","object?",false,{"string",nullptr,nullptr},1},
    {"interaction_target","string",false,{nullptr,nullptr,nullptr},0},
    {"has","boolean",false,{"string",nullptr,nullptr},1},
    {"remove_component","void",true,{"string",nullptr,nullptr},1},
    {"spawn","void",true,{"string","string","array"},3},
    {"alive","boolean",false,{nullptr,nullptr,nullptr},0},
    {"action","boolean",false,{"string",nullptr,nullptr},1},
    {"pressed","boolean",false,{"string",nullptr,nullptr},1},
    {"move","void",true,{"number","number","boolean"},3},
    {"destroy","void",true,{nullptr,nullptr,nullptr},0},
    {"load_level","void",true,{"string",nullptr,nullptr},1},
    {"audio_play","void",true,{nullptr,nullptr,nullptr},0},
    {"ui_text","void",true,{"string","string",nullptr},2},
    {"get","value",false,{"string","string",nullptr},2},
    {"set","void",true,{"string","string","value"},3},
};
} // namespace azurerender
