// Generated by tools/generate_shader_types.py.
#pragma once
#include <cstddef>
#include <cstdint>
namespace azurerender::shader {
struct BloomParameters {
    float threshold = 1.2F;
    std::uint32_t extractBright = 0U;
};
static_assert(sizeof(BloomParameters) == 8);
static_assert(alignof(BloomParameters) == 4);
static_assert(offsetof(BloomParameters, threshold) == 0);
static_assert(offsetof(BloomParameters, extractBright) == 4);
}
