#include "assets/GeneratorRegistry.hpp"
#include "runtime/AssetDatabase.hpp"
#include <fstream>
#include <iostream>
using namespace azurerender;
using Json=nlohmann::json;
void check(bool condition,const char* message) { if(!condition)throw std::runtime_error(message); }
template<class F> void rejects(F f) { bool bad=false;try{f();}catch(const std::exception&){bad=true;}check(bad,"Expected invalid generated asset rejection"); }
void write(const std::filesystem::path& p,const std::string& data) { std::ofstream(p,std::ios::binary)<<data; }
int main() {
    const auto root=std::filesystem::temp_directory_path()/"azure generation contracts";
    std::filesystem::remove_all(root);
    try {
        GeneratorRegistry generators;
        generators.add("text.copy",1,[](const GenerationRequest& r){return r.inputs.at(0).bytes;});
        generators.add("broken",1,[](const GenerationRequest&)->std::string{throw std::runtime_error("Compiler failed");});
        rejects([&]{generators.add("text.copy",1,[](const auto&){return std::string();});});
        rejects([&]{generators.add("invalid",0,[](const auto&){return std::string();});});
        const std::vector<std::pair<std::string,std::string>> fixtures={
            {"level.azurelevel",R"({"schemaVersion":1,"id":"generated","sceneType":"sample","resources":[],"nodes":[]})"},
            {"body.azureprefab",R"({"schemaVersion":1,"id":"generated","resources":[],"nodes":[]})"},
            {"motion.json",R"({"schemaVersion":1,"initial":"idle","states":[{"name":"idle","clip":0}],"transitions":[]})"},
            {"data.bin",std::string("binary\0input",12)}};
        std::vector<std::string> fingerprints;
        for(const char* folder:{"exploration","inspector"}) {
            const auto path=root/folder;Project::create(path,folder);AssetDatabase db(Project::load(path/"project.azureproject"));
            db.refresh();
            for(const auto& fixture:fixtures) {
                const auto source="assets:/"+fixture.first+".source",dependency="assets:/"+fixture.first+".dependency";
                write(path/"assets"/(fixture.first+".source"),fixture.second);write(path/"assets"/(fixture.first+".dependency"),"v1");db.refresh(true);
                const auto output="assets:/"+fixture.first;
                const auto id=db.generateAsset(generators,"text.copy",output,Json::object(),{source},{dependency},"LicenseRef-Project",[](const std::string&){},{});
                const auto record=db.records().at(id);check(db.readSource(id)==fixture.second,"Generated bytes round trip");
                check(record.generation.has_value(),"Generation manifest persisted");
                fingerprints.push_back(record.generation->fingerprint());
                const auto again=db.generateAsset(generators,"text.copy",output,Json::object(),{source},{dependency},"LicenseRef-Project",[](const auto&){},{});
                check(again==id,"Resource identity survives regeneration");
                const auto cache=db.cacheFile(id);const auto version=record.fingerprint;
                rejects([&]{db.generateAsset(generators,"broken",output,Json::object(),{}, {},"LicenseRef-Project",[](const auto&){},{});});
                rejects([&]{db.generateAsset(generators,"text.copy",output,Json::object(),{source},{},"LicenseRef-Project",[](const auto&){throw std::runtime_error("Invalid content");},{});});
                rejects([&]{db.generateAsset(generators,"text.copy",output,Json::object(),{source},{},"LicenseRef-Project",[](const auto&){},[]{throw std::runtime_error("Cancelled");});});
                check(db.records().at(id).fingerprint==version&&std::filesystem::exists(cache)&&db.readSource(id)==fixture.second,"Failure keeps effective cache and UUID");
            }
            const auto id=db.idForPath("assets:/data.bin");const auto original=db.readSource(id);
            write(path/"assets/data.bin","tampered");rejects([&]{db.refresh(true);});
            check(db.readSource(id)==original,"Tamper rejection keeps active cache");write(path/"assets/data.bin",original);
            write(path/"assets/data.bin.dependency","v2");rejects([&]{db.refresh(true);});
            const auto oldFingerprint=db.records().at(id).fingerprint;
            db.generateAsset(generators,"text.copy","assets:/data.bin",Json::object(),{"assets:/data.bin.source"},{"assets:/data.bin.dependency"},"LicenseRef-Project",[](const auto&){},{});
            check(oldFingerprint!=db.records().at(id).fingerprint,"Dependency update produces a fresh version");
            rejects([&]{db.generateAsset(generators,"text.copy","assets:/../escape.bin",Json::object(),{"assets:/data.bin.source"},{},"LicenseRef-Project",[](const auto&){},{});});
            rejects([&]{db.generateAsset(generators,"text.copy","assets:/data.bin",Json::object(),{"assets:/data.bin"},{},"LicenseRef-Project",[](const auto&){},{});});
            db.writePack(path/"pack");check(AssetDatabase::resolvePack(path/"pack",id).filename()=="data.bin","Pack retains output");
            rejects([&]{db.generateAsset(GeneratorRegistry::builtins(),"azure.text","assets:/invalid.json",{{"source",R"({"schemaVersion":1,"initial":"missing","states":[],"transitions":[]})"}},{},{},"LicenseRef-Project",[](const auto&){},{});});
            check(!std::filesystem::exists(path/"assets/invalid.json"),"Domain rejection removes uncommitted output");
            auto packed=Json::parse(std::ifstream(path/"pack/assets/data.bin.azmeta"));check(packed.contains("generation"),"Pack retains provenance");
            std::filesystem::rename(path,root/(std::string(folder)+" moved"));
            AssetDatabase moved(Project::load(root/(std::string(folder)+" moved")/"project.azureproject"));moved.refresh(true);
            check(moved.readSource(id)==original,"Moved project retains UUID and content");
        }
        check(fingerprints[0]==fingerprints[4],"Two projects share deterministic generator provenance");
        const auto budgetRoot=root/"budget";Project::create(budgetRoot,"budget");
        write(budgetRoot/"assets/input.source","initial");
        AssetDatabase budgetDb(Project::load(budgetRoot/"project.azureproject"));budgetDb.refresh(true);
        const auto source=budgetRoot/"assets/input.source";
        std::filesystem::resize_file(source,256ULL*1024*1024+1);
        std::string budgetError;
        try { budgetDb.generateAsset(generators,"text.copy","assets:/output.bin",Json::object(),{"assets:/input.source"},{},"LicenseRef-Project",[](const auto&){},{}); }
        catch(const std::exception& e){budgetError=e.what();}
        check(budgetError=="Generation source byte budget exceeded","Source budget must be checked before reading");
        write(source,std::string(192*1024,'x'));unsigned checkpoints=0;
        std::string changedError;
        try { budgetDb.generateAsset(generators,"text.copy","assets:/output.bin",Json::object(),{"assets:/input.source"},{},"LicenseRef-Project",[](const auto&){},[&]{if(++checkpoints==3)std::filesystem::resize_file(source,200*1024);}); }
        catch(const std::exception& e){changedError=e.what();}
        check(changedError=="Generation source changed during read","Changing source must fail during chunked read");
        write(source,std::string(192*1024,'x'));checkpoints=0;
        rejects([&]{budgetDb.generateAsset(generators,"text.copy","assets:/output.bin",Json::object(),{"assets:/input.source"},{},"LicenseRef-Project",[](const auto&){},[&]{if(++checkpoints==3)throw std::runtime_error("Cancelled read");});});
        check(!std::filesystem::exists(budgetRoot/"assets/output.bin"),"Read cancellation keeps output uncommitted");
        GenerationRequest request;request.licenseSource="LicenseRef-Project";request.outputReference="assets:/x";
        request.inputs.push_back({"assets:/source","bytes"});
        const auto good=generators.generate("text.copy",request);
        auto manifest=good.manifest.toJson();manifest["schemaVersion"]=2;rejects([&]{GenerationManifest::fromJson(manifest);});
        manifest=good.manifest.toJson();manifest["schemaVersion"]=1.0;rejects([&]{GenerationManifest::fromJson(manifest);});
        request.licenseSource.clear();rejects([&]{generators.generate("text.copy",request);});
        std::filesystem::remove_all(root);std::cout<<"Generated content provenance, rollback, movement and pack passed\n";return 0;
    }catch(const std::exception& e) { std::cerr<<e.what()<<'\n';std::filesystem::remove_all(root);return 1; }
}
